Support rename rule for union body members
eqrion/cbindgen pull request #751
Opened 2022-04-13 08:47 UTC by kavoor

I am trying to use C++ macros to generate accessors for the fields in a rust enum. Since they are converted to SnakeCase by default, its impossible to write a macro that does this using only the original enum variant name. 

Can we add an option to support different rename rules for the union body members as well?

2022-04-13 08:50 UTC, kavoor commented
@emilio What's the time table for getting something like this into a release?

2022-04-14 15:39 UTC, emilio requested changes
This needs a test, and I think the option naming could be more consistent? But let me know if you feel strongly, I guess just `rename_fields` could be seen as renaming the `foo` in `Bar { foo: i32, bar: i32 }`, even though it wouldn't.

In terms of getting it to a release, once it's merged I'm happy to publish it right away.

2022-04-14 15:39 UTC, emilio commented on src/bindgen/config.rs
> +    pub rename_union_body_members: RenameRule,
So this is not for Rust unions (as in `union Foo {}` but C/C++ unions). I think this should just be `rename_fields` for consistency with `config.{struct,union}.rename_fields`, wdyt?

2022-04-14 15:40 UTC, emilio commented on src/bindgen/config.rs
> +    pub rename_union_body_members: RenameRule,
Maybe `rename_variant_name_field` would be more explicit? I dunno.

2022-04-15 06:43 UTC, kavoor commented
Whenever I run 'cargo test' I get errors like " panicked at 'build should succeed: CargoExpand("expand-dep", Compile("" which seem unrelated to my changes. I looked at contributing.md and only saw something about installing cython, which I did.

2022-04-15 06:51 UTC, emilio commented
On which OS? Does running `rustup override add nightly` help?

2022-04-19 08:02 UTC, kavoor commented
Thanks, that ended up being the issue! I think this should work now. Let me know if I need other tests.

2022-04-19 09:00 UTC, emilio approved these changes
Thanks, looks good!

2022-04-19 09:00 UTC, emilio commented
Ah, rustfmt is complaining about the trailing whitespace, but I can address manually, assuming all other tests pass.

2022-04-19 09:22 UTC, closed without merging